Remove west panel placement
yesamer/kie-tools pull request #4
Opened 2023-01-25 12:00 UTC by jomarko

2023-01-25 12:11 UTC, yesamer commented
@jomarko Thank you, I guess this change doesn't impact on BPMN editor, right?

2023-01-25 12:32 UTC, jomarko commented
@yesamer I am not aware of any impact for BPMN.

2023-01-26 08:39 UTC, yesamer commented
@jomarko Thank you, not totally sure it is worth to totally remove that. Of course, I doubt we will need this again, so most likely this makes sense. BTW - I saw we have SOUTH defined as well, is that used?

2023-01-26 09:52 UTC, jomarko commented
@yesamer I removed 'South' placement as 97495ace61

2023-01-26 10:15 UTC, yesamer commented
@jomarko Thank you, I'll merge it just after CI build finishes with Green checks

2023-01-26 12:01 UTC, yesamer commented
@jozef GWT Compilation failed. Can you please check?

2023-01-30 14:00 UTC, jomarko commented
@yesamer thank you for spotting, pushed new commit that should solve the compilation problem.

2023-01-30 14:47 UTC, yesamer requested changes

2023-01-30 14:47 UTC, yesamer commented on packages/stunner-editors/uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/items/AbstractDockItem.java
> +        if (dock.getDockPosition() == UberfireDockPosition.EAST) {
@jomarko You forgot to remove the if block here

2023-02-02 10:03 UTC, yesamer commented
@jomarko What's the status of this PR? If you're focusing on other areas, we could discard this PR, as still not ready to be merged and is optional (from my perspective). WDTY?

2023-02-03 05:31 UTC, jomarko commented
@yesamer build is green now

2023-02-03 06:42 UTC, yesamer approved these changes
Thank you @jomarko

2023-02-03 06:42 UTC, merged